<?php defined('SYS') or exit('Access Denied!'); 
class page extends controller {
	function __construct(){
		parent::__construct();
	}
	function index(){
		$this->title = 'Welcome to Becak MVC Framework !';
		$this->meta .= meta('keywords', 'becak, php5, framework');   
		$this->head .= css('welcome.js');  
		$this->head .= script('welcome');
		
		$data['var'] = 'This page generated by Becak MVC Framework.';
		
		$this->body  = view('view_welcome', $data);

		app_view('view_base');
	}
}
?>
